"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMMAND_CATEGORIES = void 0;
exports.COMMAND_CATEGORIES = [
    'moderation',
    'administration',
    'automod',
    'server',
    'channel',
    'roles',
    'user',
    'utility',
    'general',
    'information',
    'welcome',
    'goodbye',
    'logging',
    'tickets',
    'giveaways',
    'leveling',
    'economy',
    'reaction',
    'verification',
    'automation',
    'suggestions',
    'starboard',
    'voice',
    'music',
    'security',
    'anti-raid',
    'backup',
    'embeds',
    'developer',
    'owner',
    'configuration',
    'fun',
    'forms',
    'social',
];
